cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  name: ${NODE_NAME}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}
network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log

bootstrap:
  memory_lock: ${MEMORY_LOCK}

#https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html#modules-http  
http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

discovery:
  zen:
    minimum_master_nodes: ${NUMBER_OF_MASTERS}
#https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_config_file_format
#https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html